# Disable multiple versions lint since we can't control transitive dependencies
multiple_crate_versions = { allow = true }

# Disable struct excessive bools lint as App structure needs many boolean flags
struct_excessive_bools = { allow = true }

# Allow complex functions
too_many_lines = { threshold = 300 }
cognitive_complexity_threshold = 50

# Settings for performance lints
significant_drop_in_scrutinee = { allow = true }
significant_drop_tightening = { allow = true }

# Allow missing error documentation as it's a development tool
missing_errors_doc = { allow = true }

# Allow unwrapped returns for command processing
unnecessary_wraps = { allow = true }

# Allow vec indexing in specific cases
match_on_vec_items = { allow = true }

# Allow string formatting style
uninlined_format_args = { allow = true }

# Allow underscore bindings when they make sense
used_underscore_binding = { allow = true }

# Allow sign loss in specific integer conversions
cast_sign_loss = { allow = true }

# Allow pass by value for ergonomic event handling
needless_pass_by_value = { allow = true }

# Allow items after statements
items_after_statements = { allow = true }

# Allow branches sharing code in specific cases
branches_sharing_code = { allow = true }

# Allow if-let versus equality variants
equatable_if_let = { allow = true }

# Allow option_if_let_else for readability
option_if_let_else = { allow = true }

# Allow manual let else patterns
manual_let_else = { allow = true }

# Allow match arms with identical bodies for clearer code
match_same_arms = { allow = true } 