# Temporarily allow these lints until they can be fixed properly
pub-underscore-fields = "allow"
cast-possible-truncation = "allow"
cast-possible-wrap = "allow"
struct-field-names = "allow"
format-push-string = "allow"
unused-self = "allow"
missing-panics-doc = "allow"
cast-precision-loss = "allow"
return-self-not-must-use = "allow"
collection-is-never-read = "allow" 