name: Linux

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 3'  # Run weekly on Wednesdays
  workflow_dispatch:     # Allow manual triggering

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  compatibility:
    runs-on: ubuntu-latest
    name: Linux Compatibility Check

    steps:
    - uses: actions/checkout@v4
    
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true
    
    - name: Set up Cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check compatibility
      run: |
        echo "Checking Linux build compatibility - This is not the primary platform"
        # Only check compilation without running tests
        cargo check --all-targets

    - name: Clippy lints
      run: |
        cargo clippy --all-targets -- -A clippy::all -A clippy::pedantic -A clippy::nursery 